root = "."
tmp_dir = "tmp"

[build]
cmd = "templ generate && go build -o ./tmp/main.exe ."
bin = "./tmp/main.exe"
include_ext = ["go", "templ"]
exclude_dir = ["tmp"]
exclude_file = ["templates_templ.go"]
delay = 1000